apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eventsse.fullname" . }}
  labels:
    {{- include "eventsse.labels" . | nindent 4 }}
data:
  EVENTSSE_PORT: "{{ .Values.service.port }}"
  EVENTSSE_DEBUG: "{{ .Values.env.EVENTSSE_DEBUG }}"
  EVENTSSE_CORS: "{{ .Values.env.EVENTSSE_CORS }}"
  EVENTSSE_DUMP_ENV: "{{ .Values.env.EVENTSSE_DUMP_ENV }}"
  EVENTSSE_QUEUE_MAX_CAPACITY: "{{ .Values.env.EVENTSSE_QUEUE_MAX_CAPACITY }}"
  EVENTSSE_QUEUE_WORKER_THREADS: "{{ .Values.env.EVENTSSE_QUEUE_WORKER_THREADS }}"
