apiVersion: eventrouter.krateo.io/v1alpha1
kind: Registration
metadata:
  name: eventsse
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: Eventrouter SSE
  endpoint: http://{{ include "eventsse.fullname" . }}-internal.{{ .Release.Namespace }}.svc.cluster.local/handle
