apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventsse.fullname" . }}-internal
  labels:
    {{- include "eventsse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: eventrouter
  selector:
    {{- include "eventsse.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventsse.fullname" . }}-external
  labels:
    {{- include "eventsse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: sse
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}  
  selector:
    {{- include "eventsse.selectorLabels" . | nindent 4 }}
